### PR TITLE
Specify required pages

### PR DESCRIPTION
**Pull request by kenvandine**

### CODE REVIEW

**Review by seb128 — COMMENTED** [review]
Seems ok to me but I've not tested ubuntu-provision before. What's the behavior today without that definition? Is that for the installer or the welcome wizard?

**Comment by kenvandine** [comment]
> Seems ok to me but I've not tested ubuntu-provision before. What's the behavior today without that definition? Is that for the installer or the welcome wizard?

That's for the installer

**Comment by seb128** [comment]
Could you also reply to the question of what happens without that list? It would be better if we didn't have to ensure one extra file is kept uptodate for the installer default to do the right thing. It seems it's not needed today which is less manual work to do than having to keep the lists in sync manually?

**Review by seb128 — APPROVED** [review]
alright, thanks

**Pull request merged**
